# Generated by Django 3.2 on 2023-01-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0004_rename_user_utilizatori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizatori',
            old_name='name',
            new_name='username',
        ),
    ]
